// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace POSMLModel_ConsoleApp1
{
    public partial class POSMLModel
    {
        /// <summary>
        /// model input class for POSMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Sales_Id")]
            public float Sales_Id { get; set; }

            [ColumnName(@"Order_Name")]
            public string Order_Name { get; set; }

            [ColumnName(@"Customer_Name")]
            public string Customer_Name { get; set; }

            [ColumnName(@"Product_Name")]
            public string Product_Name { get; set; }

            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"Unit_Price")]
            public float Unit_Price { get; set; }

            [ColumnName(@"Total")]
            public float Total { get; set; }

            [ColumnName(@"Sales_Date")]
            public string Sales_Date { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for POSMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Sales_Id")]
            public float Sales_Id { get; set; }

            [ColumnName(@"Order_Name")]
            public float[] Order_Name { get; set; }

            [ColumnName(@"Customer_Name")]
            public float[] Customer_Name { get; set; }

            [ColumnName(@"Product_Name")]
            public float[] Product_Name { get; set; }

            [ColumnName(@"Quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"Unit_Price")]
            public float Unit_Price { get; set; }

            [ColumnName(@"Total")]
            public float Total { get; set; }

            [ColumnName(@"Sales_Date")]
            public string Sales_Date { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("POSMLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
