
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace POSMLModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            POSMLModel.ModelInput sampleData = new POSMLModel.ModelInput()
            {
                Order_Name = @"Order2",
                Customer_Name = @"Customer2",
                Product_Name = @"Drawer Lock 132-22mm",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = POSMLModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Total with predicted Total from sample data...\n\n");


            Console.WriteLine($"Order_Name: {@"Order2"}");
            Console.WriteLine($"Customer_Name: {@"Customer2"}");
            Console.WriteLine($"Product_Name: {@"Drawer Lock 132-22mm"}");
            Console.WriteLine($"Total: {120F}");


            Console.WriteLine($"\n\nPredicted Total: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
